Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 97, in taster
    abbr = abbr_finder(quarters[0][drive_count],abbr)
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 97, in taster
    abbr = abbr_finder(quarters[0][drive_count],abbr)
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 97, in taster
    abbr = abbr_finder(quarters[0][drive_count],abbr)
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 97, in taster
    abbr = abbr_finder(quarters[0][drive_count],abbr)
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 97, in taster
    abbr = abbr_finder(quarters[0][drive_count],abbr)
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 97, in taster
    abbr = abbr_finder(quarters[0][drive_count],abbr)
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 97, in taster
    abbr = abbr_finder(quarters[0][drive_count],abbr)
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 97, in taster
    abbr = abbr_finder(quarters[0][drive_count],abbr)
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 97, in taster
    abbr = abbr_finder(quarters[0][drive_count],abbr)
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 97, in taster
    abbr = abbr_finder(quarters[0][drive_count],abbr)
IndexError: list index out of range
